#!/usr/bin/env python3
import os
import sys


def main() -> int:
    args = sys.argv[1:]
    if not args:
        return 1
    if args[0] == "-f":
        if len(args) < 2:
            return 1
        print(os.path.realpath(args[1]))
        return 0
    print(os.path.realpath(args[0]))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
